'use client'

import type React from 'react'
import { createContext, useState, useContext } from 'react'

// List of translations for the text in the Skydd-app
// List contains English, Norwegian and Swedish text
const translations = {
  en: {
    greeting: 'Hello',
    settings: 'Settings',
    notifications: 'Notifications',
    pushNotifications: 'Push Notifications',
    weatherAlerts: 'Weather Alerts',
    accessibility: 'Accessibility',
    darkMode: 'Dark Mode',
    language: 'Language',
    home: 'Home',
    coursesTab: 'Courses',
    profile: 'Profile',

    readyForTrip: 'Ready for a new trip?',
    start: 'START',
    map: 'Map',
    viewOurCourses: 'View our courses',

    courses: 'Courses',
    basicSeamanship: 'Basic Seamanship',
    navigationAtSea: 'Navigation at Sea',
    lanternAtSea: 'Lanterns at Sea',
    safetyAtSea: 'Safety at Sea',

    personalInfo: 'Personal Information',
    myBoats: 'My Boats',
    contacts: 'Contacts',
    previousTrips: 'Previous Trips',
    logout: 'Log out',
    loading: 'Loading...',
    goBack: 'Go Back',

    selectBoat: 'Select Boat',
    whichBoatToUse: 'Which boat would you like to use?',
    tryAgain: 'Try Again',
    noBoatsAdded: 'No boats added',
    addBoatBeforeRiskAssessment:
      'You need to add a boat before starting a risk assessment.',
    hp: 'HP',
    addNewBoat: 'Add New Boat',
    sailboat: 'Sailboat',
    motorboat: 'Motorboat',

    riskAssessment: 'Risk Assessment',
    safetyTestFor: 'Safety Test for',
    boatTrip: 'boat trip',
    question: 'Question',
    of: 'of',
    back: 'Back',
    yes: 'Yes',
    no: 'No',
    tapToChangeAnswer: 'Tap to change answer',
    retrievedFromProfile: 'Retrieved from profile',
    howManyPeopleOnboard: 'How many people are onboard?',
    thisBoatHasMaxCapacity: 'This boat has a maximum capacity of',
    people: 'people',
    warning: 'WARNING',
    tooManyPassengersForThisBoat: 'Too many passengers for this boat!',
    confirm: 'Confirm',
    boat: 'Boat',
    risk: 'risk',
    critical: 'Critical',
    low: 'Low',
    moderate: 'Moderate',
    high: 'High',
    extreme: 'Extreme',
    tooManyPassengers: 'Too many passengers',
    boatCapacityLimitMessage: 'This boat only has room for',
    reducePassengersToStart:
      'Reduce the number of passengers to start the trip.',
    excellent: 'Excellent! You are well prepared for the trip.',
    yourTotalRiskScore: 'Your total risk score is',
    wellPreparedButCheck:
      'You are well prepared, but check the items you answered no to.',
    considerImprovingSafety: 'Consider improving safety before heading out.',
    stronglyRecommendImproving:
      'It is strongly recommended to improve safety before heading out.',
    numberOfPeopleOnboard: 'Number of people onboard',
    max: 'max',
    cannotStartTrip: 'Cannot start trip',
    startTrip: 'Start trip',
    backToHome: 'Back to home',
    tooManyPassengersWarning:
      'Too many passengers! This boat only has room for',
    couldNotSaveRiskAssessment:
      'Could not save risk assessment. Please try again later.',
    error: 'Error',
    unknownError: 'Unknown error',

    areThereMorePeopleOnboard: 'Are there more people onboard?',
    haveYouReportedWhereYouAreGoing: 'Have you reported where you are going?',
    doesEveryoneHaveLifeJackets: 'Does everyone have life jackets?',
    doYouKnowWhoToCallForHelp: 'Do you know who to call for help?',
    haveYouCheckedWeatherForecast: 'Have you checked the weather forecast?',
    doYouHaveEnoughPhoneBattery: 'Do you have enough phone battery?',
    doYouHaveWaterOnboard: 'Do you have water/drinks onboard?',
    isThereEnoughFuel: 'Is there enough fuel?',
    doYouKnowWhatToDoIfEngineStops:
      'Do you know what to do if the engine stops?',
    doYouKnowWhatToDoIfSomeoneOverboard:
      'Do you know what to do if someone falls overboard?',
    doYouKnowWhatToDoIfFireOnboard:
      'Do you know what to do if there is a fire onboard?',
    doYouHaveFlashlightOnboard:
      "Do you have a flashlight onboard (if it's evening)?",
    areYouFamiliarWithArea: 'Are you familiar with the area?',
    doYouHaveAccessToMaps: 'Do you have access to maps?',
    isThereAnchorOnboard: 'Is there an anchor onboard?',
    isBailingScoopAvailable: 'Is a bailing scoop available?',
    doYouHaveBoatingLicense: 'Do you have a boating license?',
    areYouFamiliarWithNavigationRules:
      'Are you familiar with navigation rules?',
    isBoatUnder8Meters: 'Is the boat under 8 meters?',
    isEngineUnder25HP: 'Is the engine under 25 HP?',
    areYouUnder16YearsMax10HP:
      'Are you under 16 years? Then max 10 HP is allowed',

    safetyTestComplete: 'Safety test completed',
    smsNotAvailable: 'SMS is not available on this device.',
    smsSendError: 'There was an error sending the SMS.',
    sendSms: 'Send SMS with test result',

    ongoingTrip: 'Ongoing Trip',
    location: 'Location',
    time: 'Time',
    weather: 'Weather',
    wind: 'Wind',
    sendMyLocation: 'Send my location',
    endTrip: 'End Trip',
    confirmEndTrip: 'Are you sure you want to end the trip?',
    cancel: 'Cancel',
    end: 'End',
    yourPosition: 'Your position',
    unknown: 'Unknown',
    notAvailable: 'Not available',
    unknownLocation: 'Unknown location',
    noLocationAvailable: 'No location available',
    permissionDenied: 'Permission denied',
    locationPermissionNeeded:
      'We need access to your location to track your trip.',
    locationTrackingError: 'Could not start location tracking.',
    helloHereIsMyLocation: 'Hello, here is my location',
    latitude: 'Latitude',
    longitude: 'Longitude',
    hourShort: 'h',
    minuteShort: 'm',

    clear: 'Clear',
    partlyCloudy: 'Partly cloudy',
    cloudy: 'Cloudy',
    rainShowers: 'Rain showers',
    rainShowersAndThunder: 'Rain showers and thunder',
    sleetShowers: 'Sleet showers',
    snowShowers: 'Snow showers',
    rain: 'Rain',
    heavyRain: 'Heavy rain',
    heavyRainAndThunder: 'Heavy rain and thunder',
    sleet: 'Sleet',
    snow: 'Snow',
    snowAndThunder: 'Snow and thunder',
    fog: 'Fog',
    sleetShowersAndThunder: 'Sleet showers and thunder',
    snowShowersAndThunder: 'Snow showers and thunder',
    rainAndThunder: 'Rain and thunder',
    sleetAndThunder: 'Sleet and thunder',
    lightRainShowersAndThunder: 'Light rain showers and thunder',
    heavyRainShowersAndThunder: 'Heavy rain showers and thunder',
    lightSleetShowersAndThunder: 'Light sleet showers and thunder',
    heavySleetShowersAndThunder: 'Heavy sleet showers and thunder',
    lightSnowShowersAndThunder: 'Light snow showers and thunder',
    heavySnowShowersAndThunder: 'Heavy snow showers and thunder',
    lightRainAndThunder: 'Light rain and thunder',
    lightSleetAndThunder: 'Light sleet and thunder',
    heavySleetAndThunder: 'Heavy sleet and thunder',
    lightSnowAndThunder: 'Light snow and thunder',
    heavySnowAndThunder: 'Heavy snow and thunder',
    lightRain: 'Light rain',
    lightSleet: 'Light sleet',
    heavySleet: 'Heavy sleet',
    lightSnow: 'Light snow',
    heavySnow: 'Heavy snow',
    lightRainShowers: 'Light rain showers',
    heavyRainShowers: 'Heavy rain showers',
    lightSleetShowers: 'Light sleet showers',
    heavySleetShowers: 'Heavy sleet showers',
    lightSnowShowers: 'Light snow showers',
    heavySnowShowers: 'Heavy snow showers',

    selectContact: 'Select contact',
    noContactsFound: 'No contacts found',
    emergencyCalls: 'Emergency Calls',
    slideToCall: 'Slide to call',
    police: 'Police',
    coastGuardRadio: 'Coast Guard Radio',
  },
  no: {
    greeting: 'Hei',
    settings: 'Innstillinger',
    notifications: 'Varsler',
    pushNotifications: 'Pushvarslinger',
    weatherAlerts: 'Værvarsel',
    accessibility: 'Tilgjengelighet',
    darkMode: 'Lys/mørk modus',
    language: 'Språk',
    home: 'Hjem',
    coursesTab: 'Kurs',
    profile: 'Profil',

    readyForTrip: 'Klar for en ny tur?',
    start: 'START',
    map: 'Kart',
    viewOurCourses: 'Se våre kurs',

    courses: 'Kurs',
    basicSeamanship: 'Grunnleggende sjøvett',
    navigationAtSea: 'Navigasjon på sjøen',
    lanternAtSea: 'Lanterne på sjøen',
    safetyAtSea: 'Sikkerhet på sjøen',

    personalInfo: 'Personlig informasjon',
    myBoats: 'Mine båter',
    contacts: 'Kontakter',
    previousTrips: 'Tidligere turer',
    logout: 'Logg ut',
    loading: 'Laster...',
    goBack: 'Gå tilbake',

    selectBoat: 'Velg båt',
    whichBoatToUse: 'Hvilken båt du skal bruke?',
    tryAgain: 'Prøv igjen',
    noBoatsAdded: 'Ingen båter lagt til',
    addBoatBeforeRiskAssessment:
      'Du må legge til en båt før du kan starte en risikovurdering.',
    hp: 'HK',
    addNewBoat: 'Legg til ny båt',
    sailboat: 'Seilbåt',
    motorboat: 'Motorbåt',

    riskAssessment: 'Risikovurdering',
    safetyTestFor: 'Sikkerhetstest for',
    boatTrip: 'båttur',
    question: 'Spørsmål',
    of: 'av',
    back: 'Tilbake',
    yes: 'Ja',
    no: 'Nei',
    tapToChangeAnswer: 'Trykk for å endre svar',
    retrievedFromProfile: 'Hentet fra profil',
    howManyPeopleOnboard: 'Hvor mange personer er ombord?',
    thisBoatHasMaxCapacity: 'Denne båten har plass til maks',
    people: 'personer',
    warning: 'Advarsel',
    tooManyPassengersForThisBoat: 'For mange passasjerer for denne båten!',
    confirm: 'Bekreft',
    boat: 'Båt',
    risk: 'risiko',
    critical: 'Kritisk',
    low: 'Lav',
    moderate: 'Moderat',
    high: 'Høy',
    extreme: 'Ekstrem',
    tooManyPassengers: 'For mange passasjerer',
    boatCapacityLimitMessage: 'Denne båten har kun plass til',
    reducePassengersToStart: 'Reduser antall passasjerer for å starte turen.',
    excellent: 'Utmerket! Du er godt forberedt for turen.',
    yourTotalRiskScore: 'Din totale risiko-score er',
    wellPreparedButCheck:
      'Du er godt forberedt, men sjekk punktene du svarte nei på.',
    considerImprovingSafety: 'Vurder å forbedre sikkerheten før du drar ut.',
    stronglyRecommendImproving:
      'Det anbefales sterkt å forbedre sikkerheten før du drar ut.',
    numberOfPeopleOnboard: 'Antall personer ombord',
    max: 'maks',
    cannotStartTrip: 'Kan ikke starte tur',
    startTrip: 'Start tur',
    backToHome: 'Tilbake til hjem',
    tooManyPassengersWarning:
      'For mange passasjerer! Denne båten har kun plass til',
    couldNotSaveRiskAssessment:
      'Kunne ikke lagre risikovurdering. Prøv igjen senere.',
    error: 'Feil',
    unknownError: 'Ukjent feil',

    areThereMorePeopleOnboard: 'Er det flere personer ombord?',
    haveYouReportedWhereYouAreGoing: 'Har du meldt fra hvor du skal?',
    doesEveryoneHaveLifeJackets: 'Har alle redningsvester?',
    doYouKnowWhoToCallForHelp: 'Vet du hvor du kan ringe om du trenger hjelp?',
    haveYouCheckedWeatherForecast: 'Har du sjekket værmeldingen?',
    doYouHaveEnoughPhoneBattery: 'Har du nok strøm på mobilen?',
    doYouHaveWaterOnboard: 'Har du vann/drikke i båten?',
    isThereEnoughFuel: 'Er det nok drivstoff?',
    doYouKnowWhatToDoIfEngineStops:
      'Vet du hva du skal gjøre om motoren stopper?',
    doYouKnowWhatToDoIfSomeoneOverboard:
      'Vet du hva du skal gjøre om noen faller over bord?',
    doYouKnowWhatToDoIfFireOnboard:
      'Vet du hva du skal gjøre om det oppstår brann om bord?',
    doYouHaveFlashlightOnboard:
      'Lykt eller lommelykt i båten (om det er kveld)',
    areYouFamiliarWithArea: 'Er du kjent i området?',
    doYouHaveAccessToMaps: 'Har du tilgang til kart?',
    isThereAnchorOnboard: 'Er det dregg/anker i båten?',
    isBailingScoopAvailable: 'Er det øsekar tilgjengelig?',
    doYouHaveBoatingLicense: 'Har du båtførerbevis?',
    areYouFamiliarWithNavigationRules: 'Kjenner du til sjøveisreglene?',
    isBoatUnder8Meters: 'Er båten under 8 meter?',
    isEngineUnder25HP: 'Er motoren under 25 hk?',
    areYouUnder16YearsMax10HP: 'Er du under 16 år? Da er det maks 10 hk',

    safetyTestComplete: 'Sikkerhetstesten er fullført',
    smsNotAvailable: 'SMS er ikke tilgjengelig på denne enheten.',
    smsSendError: 'Det oppstod en feil ved sending av SMS.',
    sendSms: 'Send SMS med testresultat',

    ongoingTrip: 'Underveis',
    location: 'Plassering',
    time: 'Tid',
    weather: 'Vær',
    wind: 'Vind',
    sendMyLocation: 'Send min lokasjon',
    endTrip: 'Avslutt tur',
    confirmEndTrip: 'Er du sikker på at du vil avslutte turen?',
    cancel: 'Avbryt',
    end: 'Avslutt',
    yourPosition: 'Din posisjon',
    unknown: 'Ukjent',
    notAvailable: 'Ikke tilgjengelig',
    unknownLocation: 'Ukjent sted',
    noLocationAvailable: 'Ingen lokasjon tilgjengelig',
    permissionDenied: 'Tillatelse avslått',
    locationPermissionNeeded:
      'Vi trenger tilgang til din posisjon for å spore turen din.',
    locationTrackingError: 'Kunne ikke starte posisjonssporing.',
    helloHereIsMyLocation: 'Hei, her er min lokasjon',
    latitude: 'Breddegrad',
    longitude: 'Lengdegrad',
    hourShort: 't',
    minuteShort: 'm',

    clear: 'Klart',
    partlyCloudy: 'Lettskyet',
    cloudy: 'Skyet',
    rainShowers: 'Regnbyger',
    rainShowersAndThunder: 'Regnbyger og torden',
    sleetShowers: 'Sluddbyger',
    snowShowers: 'Snøbyger',
    rain: 'Regn',
    heavyRain: 'Kraftig regn',
    heavyRainAndThunder: 'Kraftig regn og torden',
    sleet: 'Sludd',
    snow: 'Snø',
    snowAndThunder: 'Snø og torden',
    fog: 'Tåke',
    sleetShowersAndThunder: 'Sluddbyger og torden',
    snowShowersAndThunder: 'Snøbyger og torden',
    rainAndThunder: 'Regn og torden',
    sleetAndThunder: 'Sludd og torden',
    lightRainShowersAndThunder: 'Lette regnbyger og torden',
    heavyRainShowersAndThunder: 'Kraftige regnbyger og torden',
    lightSleetShowersAndThunder: 'Lette sluddbyger og torden',
    heavySleetShowersAndThunder: 'Kraftige sluddbyger og torden',
    lightSnowShowersAndThunder: 'Lette snøbyger og torden',
    heavySnowShowersAndThunder: 'Kraftige snøbyger og torden',
    lightRainAndThunder: 'Lett regn og torden',
    lightSleetAndThunder: 'Lett sludd og torden',
    heavySleetAndThunder: 'Kraftig sludd og torden',
    lightSnowAndThunder: 'Lett snø og torden',
    heavySnowAndThunder: 'Kraftig snø og torden',
    lightRain: 'Lett regn',
    lightSleet: 'Lett sludd',
    heavySleet: 'Kraftig sludd',
    lightSnow: 'Lett snø',
    heavySnow: 'Kraftig snø',
    lightRainShowers: 'Lette regnbyger',
    heavyRainShowers: 'Kraftige regnbyger',
    lightSleetShowers: 'Lette sluddbyger',
    heavySleetShowers: 'Kraftige sluddbyger',
    lightSnowShowers: 'Lette snøbyger',
    heavySnowShowers: 'Kraftige snøbyger',

    selectContact: 'Velg kontakt',
    noContactsFound: 'Ingen kontakter funnet',
    emergencyCalls: 'Nødanrop',
    slideToCall: 'Skyv for å ringe',
    police: 'Politiet',
    coastGuardRadio: 'Kystradioen',
  },
  sv: {
    greeting: 'Hej',
    settings: 'Inställningar',
    notifications: 'Aviseringar',
    pushNotifications: 'Push-aviseringar',
    weatherAlerts: 'Vädervarningar',
    accessibility: 'Tillgänglighet',
    darkMode: 'Ljust/mörkt läge',
    language: 'Språk',
    home: 'Hem',
    coursesTab: 'Kurser',
    profile: 'Profil',

    readyForTrip: 'Redo för en ny tur?',
    start: 'STARTA',
    map: 'Karta',
    viewOurCourses: 'Se våra kurser',

    courses: 'Kurser',
    basicSeamanship: 'Grundläggande sjövett',
    navigationAtSea: 'Navigation till sjöss',
    lanternAtSea: 'lykta på havet',
    safetyAtSea: 'Säkerhet till sjöss',

    personalInfo: 'Personlig information',
    myBoats: 'Mina båtar',
    contacts: 'Kontakter',
    previousTrips: 'Tidigare resor',
    logout: 'Logga ut',
    loading: 'Laddar...',
    goBack: 'Gå tillbaka',

    selectBoat: 'Välj båt',
    whichBoatToUse: 'Vilken båt vill du använda?',
    tryAgain: 'Försök igen',
    noBoatsAdded: 'Inga båtar tillagda',
    addBoatBeforeRiskAssessment:
      'Du måste lägga till en båt innan du kan starta en riskbedömning.',
    hp: 'HK',
    addNewBoat: 'Lägg till ny båt',
    sailboat: 'Segelbåt',
    motorboat: 'Motorbåt',

    riskAssessment: 'Riskbedömning',
    safetyTestFor: 'Säkerhetstest för',
    boatTrip: 'båttur',
    question: 'Fråga',
    of: 'av',
    back: 'Tillbaka',
    yes: 'Ja',
    no: 'Nej',
    tapToChangeAnswer: 'Tryck för att ändra svar',
    retrievedFromProfile: 'Hämtad från profil',
    howManyPeopleOnboard: 'Hur många personer är ombord?',
    thisBoatHasMaxCapacity: 'Denna båt har en maxkapacitet på',
    people: 'personer',
    warning: 'VARNING',
    tooManyPassengersForThisBoat: 'För många passagerare för denna båt!',
    confirm: 'Bekräfta',
    boat: 'Båt',
    risk: 'risk',
    critical: 'Kritisk',
    low: 'Låg',
    moderate: 'Måttlig',
    high: 'Hög',
    extreme: 'Extrem',
    tooManyPassengers: 'För många passagerare',
    boatCapacityLimitMessage: 'Denna båt har endast plats för',
    reducePassengersToStart: 'Minska antalet passagerare för att starta resan.',
    excellent: 'Utmärkt! Du är väl förberedd för resan.',
    yourTotalRiskScore: 'Din totala riskpoäng är',
    wellPreparedButCheck:
      'Du är väl förberedd, men kontrollera punkterna du svarade nej på.',
    considerImprovingSafety:
      'Överväg att förbättra säkerheten innan du ger dig ut.',
    stronglyRecommendImproving:
      'Det rekommenderas starkt att förbättra säkerheten innan du ger dig ut.',
    numberOfPeopleOnboard: 'Antal personer ombord',
    max: 'max',
    cannotStartTrip: 'Kan inte starta resa',
    startTrip: 'Starta resa',
    backToHome: 'Tillbaka till hem',
    tooManyPassengersWarning:
      'För många passagerare! Denna båt har endast plats för',
    couldNotSaveRiskAssessment:
      'Kunde inte spara riskbedömningen. Försök igen senare.',
    error: 'Fel',
    unknownError: 'Okänt fel',

    safetyTestComplete: 'Säkerhetstest slutfört',
    smsNotAvailable: 'SMS är inte tillgängligt på denna enhet.',
    smsSendError: 'Det uppstod ett fel vid skickandet av SMS.',
    sendSms: 'Skicka SMS med testresultat',

    areThereMorePeopleOnboard: 'Finns det fler personer ombord?',
    haveYouReportedWhereYouAreGoing: 'Har du meddelat vart du ska?',
    doesEveryoneHaveLifeJackets: 'Har alla flytvästar?',
    doYouKnowWhoToCallForHelp: 'Vet du vem du ska ringa om du behöver hjälp?',
    haveYouCheckedWeatherForecast: 'Har du kontrollerat väderprognosen?',
    doYouHaveEnoughPhoneBattery:
      'Har du tillräckligt med batteri på telefonen?',
    doYouHaveWaterOnboard: 'Har du vatten/dryck ombord?',
    isThereEnoughFuel: 'Finns det tillräckligt med bränsle?',
    doYouKnowWhatToDoIfEngineStops: 'Vet du vad du ska göra om motorn stannar?',
    doYouKnowWhatToDoIfSomeoneOverboard:
      'Vet du vad du ska göra om någon faller överbord?',
    doYouKnowWhatToDoIfFireOnboard:
      'Vet du vad du ska göra om det uppstår brand ombord?',
    doYouHaveFlashlightOnboard: 'Ficklampa ombord (om det är kväll)',
    areYouFamiliarWithArea: 'Är du bekant med området?',
    doYouHaveAccessToMaps: 'Har du tillgång till kartor?',
    isThereAnchorOnboard: 'Finns det ett ankare ombord?',
    isBailingScoopAvailable: 'Finns det en öskar tillgänglig?',
    doYouHaveBoatingLicense: 'Har du båtkörkort?',
    areYouFamiliarWithNavigationRules: 'Känner du till sjövägsreglerna?',
    isBoatUnder8Meters: 'Är båten under 8 meter?',
    isEngineUnder25HP: 'Är motorn under 25 hk?',
    areYouUnder16YearsMax10HP: 'Är du under 16 år? Då är det max 10 hk',

    ongoingTrip: 'Pågående resa',
    location: 'Plats',
    time: 'Tid',
    weather: 'Väder',
    wind: 'Vind',
    sendMyLocation: 'Skicka min position',
    endTrip: 'Avsluta resa',
    confirmEndTrip: 'Är du säker på att du vill avsluta resan?',
    cancel: 'Avbryt',
    end: 'Avsluta',
    yourPosition: 'Din position',
    unknown: 'Okänd',
    notAvailable: 'Inte tillgänglig',
    unknownLocation: 'Okänd plats',
    noLocationAvailable: 'Ingen plats tillgänglig',
    permissionDenied: 'Tillstånd nekades',
    locationPermissionNeeded:
      'Vi behöver tillgång till din plats för att spåra din resa.',
    locationTrackingError: 'Kunde inte starta platsspårning.',
    helloHereIsMyLocation: 'Hej, här är min position',
    latitude: 'Latitud',
    longitude: 'Longitud',
    hourShort: 't',
    minuteShort: 'm',

    clear: 'Klart',
    partlyCloudy: 'Delvis molnigt',
    cloudy: 'Molnigt',
    rainShowers: 'Regnskurar',
    rainShowersAndThunder: 'Regnskurar och åska',
    sleetShowers: 'Snöblandade regnskurar',
    snowShowers: 'Snöskurar',
    rain: 'Regn',
    heavyRain: 'Kraftigt regn',
    heavyRainAndThunder: 'Kraftigt regn och åska',
    sleet: 'Snöblandat regn',
    snow: 'Snö',
    snowAndThunder: 'Snö och åska',
    fog: 'Dimma',
    sleetShowersAndThunder: 'Snöblandade regnskurar och åska',
    snowShowersAndThunder: 'Snöskurar och åska',
    rainAndThunder: 'Regn och åska',
    sleetAndThunder: 'Snöblandat regn och åska',
    lightRainShowersAndThunder: 'Lätta regnskurar och åska',
    heavyRainShowersAndThunder: 'Kraftiga regnskurar och åska',
    lightSleetShowersAndThunder: 'Lätta snöblandade regnskurar och åska',
    heavySleetShowersAndThunder: 'Kraftiga snöblandade regnskurar och åska',
    lightSnowShowersAndThunder: 'Lätta snöskurar och åska',
    heavySnowShowersAndThunder: 'Kraftiga snöskurar och åska',
    lightRainAndThunder: 'Lätt regn och åska',
    lightSleetAndThunder: 'Lätt snöblandat regn och åska',
    heavySleetAndThunder: 'Kraftigt snöblandat regn och åska',
    lightSnowAndThunder: 'Lätt snö och åska',
    heavySnowAndThunder: 'Kraftig snö och åska',
    lightRain: 'Lätt regn',
    lightSleet: 'Lätt snöblandat regn',
    heavySleet: 'Kraftigt snöblandat regn',
    lightSnow: 'Lätt snö',
    heavySnow: 'Kraftig snö',
    lightRainShowers: 'Lätta regnskurar',
    heavyRainShowers: 'Kraftiga regnskurar',
    lightSleetShowers: 'Lätta snöblandade regnskurar',
    heavySleetShowers: 'Kraftiga snöblandade regnskurar',
    lightSnowShowers: 'Lätta snöskurar',
    heavySnowShowers: 'Kraftiga snöskurar',

    selectContact: 'Välj kontakt',
    noContactsFound: 'Inga kontakter hittades',
    emergencyCalls: 'Nödsamtal',
    slideToCall: 'Svep för att ringa',
    police: 'Polis',
    coastGuardRadio: 'Kustradio',
  },
}

type Language = 'en' | 'no' | 'sv'

interface LanguageContextProps {
  language: Language
  setLanguage: (lang: Language) => void
  t: typeof translations.en
}

export const LanguageContext = createContext<LanguageContextProps>({
  language: 'no',
  setLanguage: () => {},
  t: translations.no,
})

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>('no')
  const t = translations[language]

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)

export default LanguageProvider
