'use client'

import { useEffect } from 'react'
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  SafeAreaView,
  ScrollView,
  StatusBar,
  BackHandler,
} from 'react-native'
import { useRouter } from 'expo-router'
import { useTheme } from '../context/theme-context'

// Display the terms of use at the start of the app
// IMPORTANT: The text is considered as a placeholder, and is generated by AI, and will
// have to be written by an appointed lawyer to be valid for public use.
export default function TermsPage() {
  const router = useRouter()
  const { theme } = useTheme()

  useEffect(() => {
    const backHandler = BackHandler.addEventListener(
      'hardwareBackPress',
      () => {
        return true
      }
    )

    return () => backHandler.remove()
  }, [])

  const handleAccept = () => {
    router.replace('/(tabs)/home')
  }

  const handleDecline = () => {
    router.replace('/')
  }

  return (
    <SafeAreaView
      style={[styles.container, { backgroundColor: theme.colors.primary }]}
    >
      <StatusBar barStyle="light-content" />
      <View style={styles.header}>
        <Text style={[styles.headerTitle, { color: theme.colors.white }]}>
          Vilkår og betingelser
        </Text>
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
      >
        <View style={styles.contentContainer}>
          <Text style={[styles.sectionTitle, { color: theme.colors.accent }]}>
            Nødnumre
          </Text>
          <Text style={[styles.paragraph, { color: theme.colors.white }]}>
            Ved å bruke denne applikasjonen bekrefter du at du forstår at
            nødnumrene (112, 120) KUN skal brukes i faktiske nødsituasjoner.
            Misbruk av nødnumre er straffbart og kan resultere i bøter eller
            andre konsekvenser.
          </Text>

          <Text style={[styles.sectionTitle, { color: theme.colors.accent }]}>
            Ansvarlig bruk
          </Text>
          <Text style={[styles.paragraph, { color: theme.colors.white }]}>
            Du forplikter deg til å bruke denne applikasjonen på en ansvarlig
            måte og i samsvar med gjeldende lover og forskrifter for sjøfart og
            båtbruk.
          </Text>

          <Text style={[styles.sectionTitle, { color: theme.colors.accent }]}>
            Ansvarsfraskrivelse
          </Text>
          <Text style={[styles.paragraph, { color: theme.colors.white }]}>
            Denne applikasjonen er ment som et hjelpemiddel og erstatter ikke
            god sjømannskap, kunnskap om sjøvett eller offisielle
            navigasjonshjelpemidler. Utviklerne av applikasjonen påtar seg ikke
            ansvar for skader eller tap som følge av bruk eller misbruk av
            applikasjonen.
          </Text>

          <Text style={[styles.sectionTitle, { color: theme.colors.accent }]}>
            Personvern
          </Text>
          <Text style={[styles.paragraph, { color: theme.colors.white }]}>
            Vi respekterer ditt personvern og behandler dine personopplysninger
            i henhold til gjeldende personvernlovgivning. For mer informasjon om
            hvordan vi behandler dine personopplysninger, vennligst se vår
            personvernerklæring.
          </Text>

          <Text style={[styles.sectionTitle, { color: theme.colors.accent }]}>
            Endringer i vilkårene
          </Text>
          <Text style={[styles.paragraph, { color: theme.colors.white }]}>
            Vi forbeholder oss retten til å endre disse vilkårene når som helst.
            Vesentlige endringer vil bli varslet gjennom applikasjonen. Din
            fortsatte bruk av applikasjonen etter slike endringer utgjør din
            aksept av de nye vilkårene.
          </Text>
        </View>
      </ScrollView>

      <View style={styles.buttonContainer}>
        <TouchableOpacity
          style={[
            styles.button,
            styles.declineButton,
            { borderColor: theme.colors.accent },
          ]}
          onPress={handleDecline}
        >
          <Text
            style={[styles.declineButtonText, { color: theme.colors.accent }]}
          >
            Avvis
          </Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={[
            styles.button,
            styles.acceptButton,
            { backgroundColor: theme.colors.secondary },
          ]}
          onPress={handleAccept}
        >
          <Text
            style={[styles.acceptButtonText, { color: theme.colors.white }]}
          >
            Jeg godtar
          </Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 10,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: 'Rubik-SemiBold',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  contentContainer: {
    padding: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: 'Rubik-SemiBold',
    marginTop: 16,
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 16,
    fontFamily: 'Rubik-Regular',
    marginBottom: 16,
    lineHeight: 22,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
    paddingBottom: 30,
    borderTopWidth: 1,
    borderTopColor: '#143D59',
  },
  button: {
    flex: 1,
    padding: 14,
    borderRadius: 20,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  acceptButton: {
    backgroundColor: '#F7B801',
  },
  declineButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
  },
  acceptButtonText: {
    fontSize: 16,
    fontFamily: 'Rubik-SemiBold',
  },
  declineButtonText: {
    fontSize: 16,
    fontFamily: 'Rubik-SemiBold',
  },
})
